
# List local IP addresses that can be used for outbound tcp connections
# Server process must be able to locally bind to these addresses

[[default]]
address="88.99.2.60"
name="mail.omglol.africa"

[[default]]
address="88.99.2.60"
name="omglol.africa"
#
#[[default]]
#address="1.2.3.5"
#name="ip-2.hostname"
#
