version: "3.8"
volumes:
  mongo:
  redis:
  traefik:
networks:
  captain-overlay-network:
    external: true
services: 
  wildduck:
    image: nodemailer/wildduck:v1.34.0
    restart: unless-stopped
    networks:
      - captain-overlay-network
    ports:
      - "127.0.0.1:8080:8080"
      - "143:143"
      - "110:110"
    depends_on:
      - wildduck-mongo
      - wildduck-redis
    volumes:
      - ./config/wildduck:/wildduck/config
    labels:
      traefik.enable: true
      traefik.tcp.routers.wildduck-imaps.entrypoints: imaps
      traefik.tcp.routers.wildduck-imaps.rule: HostSNI(`${HOSTNAMES}`)
      traefik.tcp.routers.wildduck-imaps.tls.certresolver: letsencrypt
      traefik.tcp.routers.wildduck-imaps.service: wildduck-imaps
      traefik.tcp.services.wildduck-imaps.loadbalancer.server.port: 143
      traefik.tcp.routers.wildduck-pop3s.entrypoints: pop3s
      traefik.tcp.routers.wildduck-pop3s.rule: HostSNI(`${HOSTNAMES}`)
      traefik.tcp.routers.wildduck-pop3s.tls.certresolver: letsencrypt
      traefik.tcp.routers.wildduck-pop3s.service: wildduck-pop3s
      traefik.tcp.services.wildduck-pop3s.loadbalancer.server.port: 110

  wildduck-webmail:
    image: nodemailer/wildduck-webmail:latest
    command: 
      - ""
    restart: unless-stopped
    networks:
      - captain-overlay-network
    depends_on:
      - wildduck-mongo
      - wildduck-redis
      - wildduck
    volumes:
      - ./config/wildduck-webmail:/app/config
    labels:
      traefik.enable: true
      # traefik.http.routers.wildduck-webmail.entrypoints: https
      traefik.http.routers.wildduck-webmail.rule: Host(`${HOSTNAMES}`)
      # traefik.http.routers.wildduck-webmail.tls.certresolver: letsencrypt
      traefik.http.services.wildduck-webmail.loadbalancer.server.port: 3000

  wildduck-zonemta:
    image: nodemailer/zonemta-wildduck
    restart: unless-stopped
    networks:
      - captain-overlay-network
    ports:
      - "587:587"
    depends_on: 
      - wildduck-mongo
      - wildduck-redis
    volumes:
      - ./config/zone-mta:/app/config
    labels:
      traefik.enable: true
      traefik.tcp.routers.wildduck-zonemta.entrypoints: smtps
      traefik.tcp.routers.wildduck-zonemta.rule: HostSNI(`${HOSTNAMES}`)
      traefik.tcp.routers.wildduck-zonemta.tls.certresolver: letsencrypt
      traefik.tcp.services.wildduck-zonemta.loadbalancer.server.port: 587

  wildduck-haraka:
    image: nodemailer/haraka-wildduck
    restart: unless-stopped
    networks:
      - captain-overlay-network
    ports:
      - "25:25"
    depends_on:
      - wildduck-mongo
      - wildduck-redis
      - wildduck-rspamd
    volumes:
      - ./config/haraka:/app/config

  wildduck-rspamd:
    image: nodemailer/rspamd
    restart: unless-stopped
    networks:
      - captain-overlay-network
    depends_on:
      - wildduck-redis
    volumes:
      - ./config/rspamd/override.d:/etc/rspamd/override.d
      - ./config/rspamd/worker-normal.conf:/etc/rspamd/worker-normal.conf
      - ./config/rspamd/local.d:/etc/rspamd/local.d

  wildduck-mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - captain-overlay-network
    volumes:
      - mongo:/data/db
    
  wildduck-redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - captain-overlay-network
    volumes:
      - redis:/data

  wildduck-traefik:
    image: traefik
    restart: unless-stopped
    networks:
      - captain-overlay-network
    command:
      - "--entrypoints.http.address=:80"
      - "--entrypoints.imaps.address=:993"
      - "--entrypoints.pop3s.address=:995"
      - "--entrypoints.smtps.address=:465"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    labels:
      traefik.enable: true
      traefik.http.routers.redirs.entrypoints: http
      traefik.http.routers.redirs.rule: hostregexp(`{host:.+}`)
    ports:
      - 80:80/tcp
      - 993:993/tcp
      - 995:995/tcp
      - 465:465/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/data